# Generated by Django 5.0.3 on 2024-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('current', models.CharField(max_length=60)),
                ('taxe_rate', models.FloatField()),
                ('logo', models.ImageField(upload_to='settings_images/')),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
