# Generated by Django 5.0.3 on 2024-04-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
