# Generated by Django 5.0.3 on 2024-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
