# Generated by Django 5.0.3 on 2024-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
