# Generated by Django 5.0.3 on 2024-04-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='reserv',
        ),
    ]
