# Generated by Django 5.0.3 on 2024-04-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_reservation_reserv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reserv',
        ),
    ]
